### ISSUE TITLE
Add support for Google Protobuf wrapper types

### ISSUE THREAD

**Issue by LarsAlmgren** [crflynn/pbspark#32]
Would it perhaps make sense to add support for Goole Protobuf common wrapper types like Int64Value and StringValue?

**Comment by crflynn** [comment]
It looks like there is some special handling in the parser/printer for these wrappers, so I think we would need to add some logic for these types. Since it's built in to protobuf's parsing I think it makes sense to add support for it here.

**Comment by crflynn** [comment]
@LarsAlmgren this should be available in 0.7.0.
