### ISSUE TITLE
Support for spark==3.1.x?

### ISSUE THREAD

**Issue by jelos98** [crflynn/pbspark#47]
Hello!

I'm interested in using `pbspark` in a project I'm working on. Unfortunately, I'm running in an spark environment that's not in my control, and as a result I need to be able to run with pyspark==3.1.2, which is problematic given that the requiremetns for `pbspark` list `pyspark>=3.2.0`

I've tested locally (though admittedly non-comprehensively) by modifying the requirements to allow pyspark==3.1.2, and it _appears_ to work fine, at least for the cases I need.

Was the requirement set at 3.2.x because you have specific reason to believe it _doesn't_ work in all cases on 3.1.x? Or was it simply a matter of 3.2.x being the version that it was developed against, and thus it's not tested against earlier versions? 

If it's the latter, would you consider relaxing the requirements (perhaps with a README caveat that 3.1.x isn't thoroughly tested?) 
If it's the former, do you recall what _doesn't_ work on earlier versions, so I don't wind up doing something that's going to come back to haunt me? 

Either way - I wanted to thank you for your work on this package.  I'm working in a world where I'm consuming literally dozens of distinct, large protobuf messages in Spark, and this package as you might imagine, becomes an _enormous_ time saver.

Kudos, and thanks!
-James

**Comment by crflynn** [comment]
I think that's just what the latest version was when I created this.

I just tested locally with python 3.8 and pyspark 3.1.1 and the tests all passed. I can relax it and make a new release for you a bit later today.

**Comment by jelos98** [comment]
Awesome!  

Thanks so much!

**Comment by crflynn** [comment]
Try 0.9.0. Feel free to re-open if you have any issues
